title: Health Information Bill
url: https://healthinfo.gov.sg
favicon: /images/Logos/moh_logo2.png
colors:
  primary-color: "#41c1ba"
  secondary-color: "#3588cb"
  media-colors:
    - title: media-color-one
      color: "#286d9e"
    - title: media-color-two
      color: "#0b87d4"
    - title: media-color-three
      color: "#0b87d4"
    - title: media-color-four
      color: "#0b87d4"
    - title: media-color-five
      color: "#0b87d4"
description: A website on the Health Information Bill
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d347474y9046ok.amplifyapp.com
prod: https://master.d347474y9046ok.amplifyapp.com
facebook-pixel: ""
shareicon: /images/moh_logo.png
is_government: true
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: news
